image: gitpod/workspace-full

tasks:
  - init: make build
    command: make dev

ports:   
  - port: 80                 # host: world.openfoodfacts.localhost
    onOpen: open-browser
    visibility: public


# Set the custom DOMAIN for Gitpod only
env:
  PRODUCT_OPENER_DOMAIN: "${GITPOD_WORKSPACE_URL}"

vscode:
  extensions:
    - richterger.perl
    # - d9705996.perl-toolbox
    - redhat.vscode-yaml
    - dbaeumer.vscode-eslint
    - stylelint.vscode-stylelint
    - syler.sass-indented
    - mrorz.language-gettext