# Gitpod Classic configuration for Open Food Facts server
# See https://www.gitpod.io/docs/config-gitpod-file

image:
  file: .gitpod/.gitpod.Dockerfile

# Define tasks to run on workspace startup
tasks:
  - name: Start development environment
    command: |
      # Use Gitpod public URL as the HOST domain so frontend loads correctly
      export PRODUCT_OPENER_DOMAIN=$(gp url 80 --public)
      # Start dev environment with updated domain
      make dev

# Expose application port and open in preview
ports:
  - port: 80
    visibility: public
    onOpen: open-browser
